parameters:
#    user.example.class: Adidas\Bundle\UserBundle\Example

services:
    sonata.user.admin.group:
       abstract: true
       public: false
    sonata.user.admin.user:
       abstract: true
       public: false
