# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Adidas\Bundle\PostBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post", label: "Post" }
        arguments:
            - ~
            - Adidas\Bundle\PostBundle\Entity\Post
            - ~