# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.challenge:
        class: Adidas\Bundle\ChallengeBundle\Admin\ChallengeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Challenge", label: "Challenge" }
        arguments:
            - ~
            - Adidas\Bundle\ChallengeBundle\Entity\Challenge
            - ~